# Generated by Django 3.2.13 on 2022-05-24 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр книги')),
            ],
            options={
                'verbose_name': 'Жанр книги',
                'verbose_name_plural': 'Жанры книг',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='ClientsOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
                ('user_name_private_room', models.CharField(max_length=50, verbose_name='Имя клиента')),
                ('user_surname_private_room', models.CharField(max_length=50, verbose_name='Фамилия клиента')),
                ('customers_passport_series', models.CharField(max_length=2, verbose_name='Серия паспорта клиента')),
                ('customers_passport_number', models.CharField(max_length=7, verbose_name='Номер паспорта клиента')),
                ('books_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private_room.booksgenre', verbose_name='Жанр книги')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин пользователя')),
            ],
            options={
                'verbose_name': 'Заказ клиента',
                'verbose_name_plural': 'Заказы клиентов',
                'ordering': ['user_name_private_room', 'user_surname_private_room'],
            },
        ),
    ]
