# Generated by Django 3.2.13 on 2022-05-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия автора')),
                ('date_of_birth', models.CharField(max_length=10, verbose_name='Дата рождения')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Таблица: Автор',
                'verbose_name_plural': 'Таблица: Авторы',
                'ordering': ['first_name', 'last_name', '-time_create'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Наименование книги')),
                ('publ_year', models.CharField(max_length=4, verbose_name='Год публикации')),
                ('book_image', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фотография')),
                ('book_price_BYN', models.PositiveIntegerField(verbose_name='Цена в BYN')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления объявления')),
                ('authors_fk', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='website.authors', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Таблица: Книга',
                'verbose_name_plural': 'Таблица: Книги',
                'ordering': ['book_name', 'book_price_BYN', 'authors_fk', '-time_create'],
            },
        ),
    ]
