# Generated by Django 3.2.13 on 2022-05-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150, verbose_name='Наименование акции')),
                ('text', models.TextField(verbose_name='Текст акции')),
                ('image_field', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Фотография ')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Таблица: Акция',
                'verbose_name_plural': 'Таблица: Акции',
                'ordering': ['header', 'text', '-time_create', 'time_update'],
            },
        ),
    ]
